id = "iwe"
name = "IWE"
description = "IWE is an open-source, local-first, markdown note-taking tool. It serves as a personal knowledge management (PKM) tool for developers."
version = "0.0.3"
schema_version = 1
authors = ["Dmytro Halichenko <dmytrohalichenko@gmail.com>"]
repository = "https://github.com/iwe-org/zed-iwe"

[language_servers.iwe]
name = "IWE"
language = "Markdown"
